faker.address.zipCode()
#---
faker.address.city()
#---
faker.address.cityPrefix()
#---
faker.address.citySuffix()
#---
faker.address.streetName()
#---
faker.address.streetAddress()
#---
faker.address.streetSuffix()
#---
faker.address.streetPrefix()
#---
faker.address.secondaryAddress()
#---
faker.address.county()
#---
faker.address.country()
#---
faker.address.countryCode()
#---
faker.address.state()
#---
faker.address.stateAbbr()
#---
faker.address.latitude()
#---
faker.address.longitude()
#---
faker.commerce.color()
#---
faker.commerce.department()
#---
faker.commerce.productName()
#---
faker.commerce.price()
#---
faker.commerce.productAdjective()
#---
faker.commerce.productMaterial()
#---
faker.commerce.product()
#---
faker.company.suffixes()
#---
faker.company.companyName()
#---
faker.company.companySuffix()
#---
faker.company.catchPhrase()
#---
faker.company.bs()
#---
faker.company.catchPhraseAdjective()
#---
faker.company.catchPhraseDescriptor()
#---
faker.company.catchPhraseNoun()
#---
faker.company.bsAdjective()
#---
faker.company.bsBuzz()
#---
faker.company.bsNoun()
#---
faker.date.past()
#---
faker.date.future()
#---
faker.date.between()
#---
faker.date.recent()
#---
faker.date.month()
#---
faker.date.weekday()
#---
faker.finance.account()
#---
faker.finance.accountName()
#---
faker.finance.mask()
#---
faker.finance.amount()
#---
faker.finance.transactionType()
#---
faker.finance.currencyCode()
#---
faker.finance.currencyName()
#---
faker.finance.currencySymbol()
#---
faker.hacker.abbreviation()
#---
faker.hacker.adjective()
#---
faker.hacker.noun()
#---
faker.hacker.verb()
#---
faker.hacker.ingverb()
#---
faker.hacker.phrase()
#---
faker.helpers.randomize()
#---
faker.helpers.slugify()
#---
faker.helpers.replaceSymbolWithNumber()
#---
faker.helpers.replaceSymbols()
#---
faker.helpers.shuffle()
#---
faker.helpers.mustache()
#---
faker.helpers.createCard()
#---
faker.helpers.contextualCard()
#---
faker.helpers.userCard()
#---
faker.helpers.createTransaction()
#---
faker.image.image()
#---
faker.image.avatar()
#---
faker.image.imageUrl()
#---
faker.image.abstract()
#---
faker.image.animals()
#---
faker.image.business()
#---
faker.image.cats()
#---
faker.image.city()
#---
faker.image.food()
#---
faker.image.nightlife()
#---
faker.image.fashion()
#---
faker.image.people()
#---
faker.image.nature()
#---
faker.image.sports()
#---
faker.image.technics()
#---
faker.image.transport()
#---
faker.internet.avatar()
#---
faker.internet.email()
#---
faker.internet.userName()
#---
faker.internet.protocol()
#---
faker.internet.url()
#---
faker.internet.domainName()
#---
faker.internet.domainSuffix()
#---
faker.internet.domainWord()
#---
faker.internet.ip()
#---
faker.internet.userAgent()
#---
faker.internet.color()
#---
faker.internet.mac()
#---
faker.internet.password()
#---
faker.lorem.words()
#---
faker.lorem.sentence()
#---
faker.lorem.sentences()
#---
faker.lorem.paragraph()
#---
faker.lorem.paragraphs()
#---
faker.name.firstName()
#---
faker.name.lastName()
#---
faker.name.findName()
#---
faker.name.jobTitle()
#---
faker.name.prefix()
#---
faker.name.suffix()
#---
faker.name.title()
#---
faker.name.jobDescriptor()
#---
faker.name.jobArea()
#---
faker.name.jobType()
#---
faker.phone.phoneNumber()
#---
faker.phone.phoneNumberFormat()
#---
faker.phone.phoneFormats()
#---
faker.random.number()
#---
faker.random.arrayElement()
#---
faker.random.objectElement()
#---
faker.random.uuid()
#---
faker.random.boolean()
